import { Metadata } from 'next'
import './globals.css'
import { Toaster } from 'react-hot-toast'

export const metadata: Metadata = {
  title: 'Product App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: any) {
  return (
    <html lang='en'>
      <body>
        <Toaster position='top-right' reverseOrder={false} />
        {children}
      </body>
    </html>
  )
}
